### ISSUE TITLE
Sample not compiling: error Couldn't find any versions for "@jsiebern/bs-material-ui" that matches "^2.1.0"

### ISSUE THREAD

**Issue by mattiasw2** [cca-io/rescript-material-ui#123]
```
$ git clone https://github.com/jsiebern/bs-material-ui.git
yarn examplesCloning into 'bs-material-ui'...
remote: Enumerating objects: 9130, done.
remote: Counting objects: 100% (1090/1090), done.
remote: Compressing objects: 100% (490/490), done.
remote: Total 9130 (delta 733), reused 777 (delta 513), pack-reused 8040
Receiving objects: 100% (9130/9130), 19.29 MiB | 5.28 MiB/s, done.
Resolving deltas: 100% (7477/7477), done.

matti@x280 MINGW64 /c/data6/rescript
$ cd bs-material-ui/public/bs-material-ui

matti@x280 MINGW64 /c/data6/rescript/bs-material-ui/public/bs-material-ui (master)
$ yarn install
yarn install v1.22.10
[1/4] Resolving packages...
warning Lockfile has incorrect entry for "@jsiebern/bs-material-ui@^2.1.0". Ignoring it.
error Couldn't find any versions for "@jsiebern/bs-material-ui" that matches "^2.1.0"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find any versions for "@jsiebern/bs-material-ui" that matches "^2.1.0"
    at MessageError.ExtendableBuiltin (C:\Users\matti\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:721:66)
    at new MessageError (C:\Users\matti\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:750:123)
    at Function.<anonymous> (C:\Users\matti\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:50546:13)
    at Generator.next (<anonymous>)
    at step (C:\Users\matti\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:310:30)
    at C:\Users\matti\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:321:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

**Comment by cknitt** [comment]
This is fixed with version 2.1.0.
